### ISSUE TITLE
Group "Custom/Domain" does not exist.

### ISSUE THREAD

**Issue by andre1400** [a-stoyanov/zabbix-domain-expiry#2]
When i try to add the template it says "Group "Custom/Domain" does not exist."

**Comment by sokeada** [comment]
you need to create new group named Custom/Domain.

**Comment by a-stoyanov** [comment]
Yes, you just need to create the group or alternatively edit the yaml config file with a group name that already exists on your server before importing.

The key you want is:
      groups:
        - name: Custom/Domain
